name: nanoid2
version: 2.1.0
description: A tiny, secure, URL-friendly, unique string ID generator, nanoid with a pure Dart API.
repository: https://github.com/passsy/nanoid2
issue_tracker: https://github.com/passsy/nanoid2/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  # Allow older lint releases for the minimum-SDK test jobs.
  lint: '>=1.5.3 <3.0.0'
  test: ^1.16.4

topics:
  - identifier
  - uuid
  - id
  - random
  - nanoid
